- name: Create EC2 instances and Route 53 Records
  hosts: local
  connection: local
  vars:
    ami_id: ami-09c813fb71547fc4f
    sg_id: sg-076be1371a703c56d
    zone_id: Z0025515EZ5XKJ77DXMH
    domain_name: srikanth-suthari.me
    instances:
    - mongo
    - mysql
  tasks:
  - name: create ec2 instance
    amazon.aws.ec2_instance:
      name: "{{ item }}"
      instance_type: t3.micro
      security_group: "{{ sg_id }}"
      image_id: "{{ ami_id }}"
      tags:
        Name: "{{ item }}"
    loop: "{{ instances }}"
    register: ec2_output

  - name: Get all public IPs
    set_fact:
      public_ips: "{{ ec2_output.results | map(attribute='instances') | flatten | map(attribute='public_ip_address') | list }}"

  - name: public ips
    ansible.builtin.debug:
      var: public_ips

  - name: Get all private IPs
    set_fact:
      private_ips: "{{ ec2_output.results | map(attribute='instances') | flatten | map(attribute='private_ip_address') | list }}"

  - name: private ips
    ansible.builtin.debug:
      var: private_ips