- name: Create EC2 instances and Route 53 Records
  hosts: local
  connection: local
  vars:
    ami_id: ami-09c813fb71547fc4f
    sg_id: sg-076be1371a703c56d
    zone_id: Z0025515EZ5XKJ77DXMH
    domain_name: srikanth-suthari.me
    instances:
    - mongo
    - mysql-a
    - frontend

  tasks:
  - name: create ec2 instance
    amazon.aws.ec2_instance:
      name: "{{ item }}"
      instance_type: t3.micro
      security_group: "{{ sg_id }}"
      image_id: "{{ ami_id }}"
      tags:
        Name: "{{ item }}"
    loop: "{{ instances }}"
    register: ec2_output

  - name: Get all public IPs set_fact
    ansible.builtin.set_fact:
    public_ips: "{{ ec2_output.results | map(attribute='instances') | flatten |
     map (attribute='public_ip_address') | list }}"

  - name: Get all private IPs set_fact
    ansible.builtin.set_fact:
    private_ips: "{{ ec2_output.results | map(attribute='instances') | flatten |
     map (attribute='private_ip_address') | list }}"

  - name: private ips
    ansible.builtin.debug:
      var: private_ips

  - name: print priveate ips
    ansible.builtin.debug:
      msg: "{{ private_ips }}"

  # - name: Create route53 record
  #   amazon.aws.route53:
  #     state: present
  #     zone: "{{ domain_name }}"
  #     record: "{{ item.item }}.{{ domain_name }}"   #This create a record for mongo and mysql as mogno.srikanth-suthari.me
  #     type: A
  #     value: "{{ item.public_ips }}"
  #     overwrite: true
  #   when: item.item == "frontend"
  #   loop: "{{ ec2_output.results }}"

  - name: create route53 record
    amazon.aws.route53:
      state: present
      zone: "{{ domain_name }}"
      record: "{{ item.item }}.{{ domain_name }}" # mongo.srikanth-suthari.me and mysql.srikanht-suthari.me
      type: A
      ttl: 1
      value: "{{ item.instances[0].private_ip_address }}"
      overwrite: true
    loop: "{{ ec2_output.results }}"

  # we are creating one record with public only for frontend
  - name: create route53 record for frontend
    amazon.aws.route53:
      state: present
      zone: "{{ domain_name }}"
      record: "{{ domain_name }}" # srikanth-suthari.me
      type: A
      ttl: 1
      value: "{{ item.instances[0].public_ip_address }}"
      overwrite: true
    when: item.item == "frontend"
    loop: "{{ ec2_output.results }}"