[catalogue]
172.31.27.231

[local]
localhost

[all:vars]
ansible_user=ece_user
ansible_password=DevOps321


#example for giving username and password
; [local:vars]
; # The variables should be assinged with '='
; Name=Srikanth
; Age=25