---
- name: Simple 'register' and 'loop' example
  hosts: localhost  # Runs on your own machine
  connection: local
  become: false      # pass the extra vars from the command line while running the playbook
  # become_ask_pass: true
  gather_facts: false

#####################
# Run this command to execute and check for the below pacages if they are installed
# ansible-playbook register-and-loop.yaml --connection=local --extra-vars "ansible_become=false"

  tasks:
    - name: Check status of several packages
      ansible.builtin.homebrew:
        name: "{{ item }}"
        state: present
      loop:
        - "git"
        - "htop"
        - "tree"
        - "python3"
      register: pkg_status # Save all loop results here

    # - name: Show a report of what happened
    #   ansible.builtin.debug:
    #     msg: "Package '{{ item.item }}' was changed: {{ item.changed }}"
    #   loop: "{{ pkg_status.results }}"
    #   loop_control:
    #     label: "{{ item.item }}"

    - name: printing the pkg_stattus variable
      ansible.builtin.debug:
        msg: "{{ pkg_status.results }}"

    # - name: print the installed packages
    #   ansible.builtin.debug:
    #     # msg: "{{ pkg_status.results | map(attribute='instances') | flatten | map(attribute='public_ip_address') | list }}"
    #     msg: "{{ pkg_status.results.item.name }}"
    #   loop: "{{ loop.item }}"