---
- name: Simple 'register' and 'loop' example
  hosts: localhost  # Runs on your own machine
  connection: local
  become: true      # Uses 'sudo' for the 'apt' command

  tasks:
    - name: Check status of several packages
      ansible.builtin.dnf:
        name: "{{ item }}"
        state: present
      loop:
        - "git"
        - "htop"
        - "tree"
      register: pkg_status # Save all loop results here

    # - name: Show a report of what happened
    #   ansible.builtin.debug:
    #     msg: "Package '{{ item.item }}' was changed: {{ item.changed }}"
    #   loop: "{{ pkg_status.results }}"
    #   loop_control:
    #     label: "{{ item.item }}"

    - name: printing the pkg_stattus variable
      ansible.builtin.debug:
        msg: "{{ pkg_status }}"